# action.yml
name: "devctl-release-bot"
description: "automatically opens PR for upstream devctl-index repo when you publish new release of your awesome plugin"
runs:
  using: "docker"
  image: "docker://alex-held/devctl-release-bot:v0.0.44"
inputs:
  workdir:
    description: "Working directory, defaults to env.GITHUB_WORKSPACE"
  devctl_template_file:
    description: "the path to template file relative to $workdir. e.g. templates/misc/plugin-name.yaml. defaults to .devctl.yaml"
