[build]
  command = "make lambda"
  functions = "functions"
  publish = "dist"
[build.environment]
  GO_IMPORT_PATH = "github.com/rajatjindal/krew-release-bot"

[[redirects]]
  from = "/github-action-webhook"
  to = "/.netlify/functions/github-action-webhook"
  status = 200