apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rajatjindal-krew-release-bot
  namespace: openfaas-fn
spec:
  encryptedData:
    krew-release-bot.yaml: AgB/wZaipVtVlRTCi5QZX+I7d1kqDBcVlF8pUG4OVDsF75rXgBZzkHIUTm/WZM44uJdcgGiLUb4zpu3eez7J1WLzoM3Do9+aG2F0eUF1O3QZj23Qqji87qND1LOrXVn+hTIRKvgcOnW7pBCn1B3kUKTnXnxX+XIuPGNjxv2xziJ2Rofa3QW7aTYBJiPOximbfMS/DywRtZ96jg2Q23acYyPzd4aqN/c3R2rMVdiKdZ44KOeIw4yLoMZuAbMCE55n9wcOSxkZqdpFsgKGvRz3scW/r0QKhyrBMonx+g/TjHHRMrOYapPAa310cooG38UPXkZmZO3pJIyTz3DC6chYw61Y8wKvagi7BQ8A5cNq4tyBW598VsKDocH7+Djr3RpSokDBxQDutqXcf+X0w9HhbybAP0nx5+nqJlj1cdCB1o7BFFzbrfrquKUmSwMAkE7x4Aj4U+1pUZXBtIymE7WIQWldpdPIfoQh8Vc9686F2nSMz3Td1s9Lwun01eIxLyRYGAzBxbAaYwpWJxQaj9+Za+fnmT4TMt/+dVkGit3Y8ZOFaxnGu5iNxSyqdwY0dh2qvtsxxmVflONaUiOato6nkUtCJKgg94hvkpIJyFDaYzrxhN5HepB+y0U+z0CXz3WsPnHiISUw+lPVz45vAERpFI2iHxVP0RENyPoTvAX4mHt3UCCRs/4QBSbJgTls3NPdhA9dpZxj803ZwPut928v5elZ51Uar0ZgVcp79hHdHfNG6k4v/AkhuLEVTaJ7Mvwvmy1Tiga8mI3dja0eXcHb0A9CndnM+X/Qnf9D49QldYwg4juOLrnXZuEDYw5trlMMPl0aBVi2U+ihP12lhXzRd8mRLTDYufjPGsBVtsD4gwV5KGTCrN7ihOy4Qsoo/Cs1T7uYtIIkeFE3NW+3+/NcetNF9kL3EfEhlu2zcHYl+RwZruk06g==
  template:
    metadata:
      creationTimestamp: null
      name: rajatjindal-krew-release-bot
      namespace: openfaas-fn
status: {}

