provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  krew-release-bot:
    lang: dockerfile
    handler: ./krew-release-bot
    image: krew-release-bot:0.1
    labels:
      com.openfaas.scale.zero: false
    secrets:
      - krew-release-bot
